### PR TITLE
added MS Windows CI buildup script

### PR DESCRIPTION
**Pull request by miroi**
Hi again,

hereby I re-adding the MS Windows CI buildup script.

### CODE REVIEW

**Comment by simensr** [comment]
I see this merge request is from July. Is it still active, and has it not been merged due to the (wrongly?) failing tests?

**Comment by miroi** [comment]
Hi,

this script has nothing to do with failing travis-ci tests. It's designed for appveyor, where buildup works, but one tests fails, see below. I suggest to accept this merge and open testing place at appveyor. Also fixing xcfun failing tests is mandatory.
.
https://ci.appveyor.com/project/miroi/xcfun/build/1.0.10
.
~~~
[ 80%] Building CXX object CMakeFiles/xcfun.dir/src/functionals/tpsslocc.cpp.obj
[ 81%] Building CXX object CMakeFiles/xcfun.dir/src/functionals/tpssx.cpp.obj
[ 83%] Building CXX object CMakeFiles/xcfun.dir/src/functionals/tw.cpp.obj
[ 84%] Building CXX object CMakeFiles/xcfun.dir/src/functionals/vonw.cpp.obj
[ 85%] Building CXX object CMakeFiles/xcfun.dir/src/functionals/vwn3.cpp.obj
[ 87%] Building CXX object CMakeFiles/xcfun.dir/src/functionals/vwn5c.cpp.obj
[ 88%] Building CXX object CMakeFiles/xcfun.dir/src/functionals/zvpbeint.cpp.obj
[ 90%] Building CXX object CMakeFiles/xcfun.dir/src/functionals/zvpbesolc.cpp.obj
[ 91%] Linking CXX static library libxcfun.a
[ 91%] Built target xcfun
Scanning dependencies of target testall
[ 92%] Building C object CMakeFiles/testall.dir/test/testall.c.obj
[ 94%] Linking CXX executable testall.exe
[ 94%] Built target testall
Scanning dependencies of target xcfun_f90_bindings
[ 95%] Building Fortran object CMakeFiles/xcfun_f90_bindings.dir/fortran/xcfun_module.F90.obj
[ 97%] Linking Fortran static library libxcfun_f90_bindings.a
[ 97%] Built target xcfun_f90_bindings
Scanning dependencies of target kernel_example
[ 98%] Building Fortran object CMakeFiles/kernel_example.dir/fortran/kernel_example.F90.obj
[100%] Linking Fortran executable kernel_example.exe
[100%] Built target kernel_example
ctest
Test project C:/projects/xcfun/build
    Start 1: testall
1/2 Test #1: testall ..........................   Passed    0.03 sec
    Start 2: kernel_example
2/2 Test #2: kernel_example ...................***Failed    0.17 sec
50% tests passed, 1 tests failed out of 2
Total Test time (real) =   0.45 sec
The following tests FAILED:
	  2 - kernel_example (Failed)
Errors while running CTest
~~~

**Comment by miroi** [comment]
" 2 - kernel_example (Failed)"  is failing on both travis-ci and appveyor-ci....

**Comment by simensr** [comment]
I agree and make the merge now

**Pull request merged**
