### PR TITLE
Drop Python 2.7 from CI jobs

### LINKED ISSUE #103: Drop Python 2.7 support
Python 2.7 has reached end-of-life. It is currently failing one of the jobs in CI. I think we should just drop it and forget it exists.

### PR DESCRIPTION
**Pull request by robertodr**
I have simplified the CI set up to only run on recent compilers. Older compilers can always be brought back at a later time. Close #103 
Plus update the license year in the source files.

## Status

- [x]  Ready to go

### CODE REVIEW

**Comment by robertodr** [comment]
Downloading GCC on macOS "breaks" Python (meaning that Python 3 is not properly put on PATH by HomeBrew) I'm tempted to drop the build. Suggestions welcome.

**Comment by bast** [comment]
Is the problem the GCC part or the Python 3 part on macOS builds?

**Comment by robertodr** [comment]
When I install GCC, also Python is reinstalled/updated and then HomeBrew will not overwrite the links to Python 2.7 Thus, to Pipenv it looks like I have no Python 3 available...

**Comment by bast** [comment]
Not sure what to say here. It would be nice to have macOS builds but neither do I have the time to struggle with that now, nor do I want to expect that time investment from others.

**Comment by robertodr** [comment]
One macOS builds would remain, so we won't be completely uncovered. And honestly given how slow the macOS builders are on Travis, I'd rather invest effort in porting macOS to Azure Pipelines...

Conclusion: I'm removing the failing one.

**Comment by robertodr** [comment]
When this is green, reviewed, and approved, please **squash-merge** it.

**Pull request merged**
