### PR TITLE
appveyor.yml, CI build for MS Windows

### PR DESCRIPTION
**Pull request by miroi**
Hey folks,

https://ci.appveyor.com/project/miroi/xcfun/build/1.0.7

here is very simple CI-buildup script for MS Windows platform, inspired with Roberto's travis-ci

Question: don't you plan  regular xcfun builds on CDash https://testboard.org  ?

(For README.md: replace my url- badge with yours, registered , the same for travis-ci - it points to Roberto's fork)

### CODE REVIEW

**Comment by miroi** [comment]
https://travis-ci.org/dftlibs/xcfun/builds/143011861

two clang tests failed; maybe there are too many of them to be testes on Linux platform; I can not restart them, could you do that ?

**Comment by uekstrom** [comment]
I am not a windows expert, but is this really how things should be done? "mkdir C:\software", isn't that like creating a directory in the root on unix?

**Comment by miroi** [comment]
mkdir C:\abc  is allowed by the virtual Windows machine;

we only have to watch not to hurt installed programs of https://ci.appveyor.com/project/miroi/xcfun/build/1.0.7#L10

**Comment by uekstrom** [comment]
Ok, I think I don't understand how this CI think works, I will let @bast decide on the merge.

**Comment by bast** [comment]
I have restarted the build. And in future we might deploy test results to testboard.org but currently I believe that the Travis (and possibly also Appveyor tests) are sufficient. I will review the Appveyor recipe in a moment.

**Comment by bast** [comment]
Also the PR is against master but master is actually old XCFun and the new development happens on ng. We will consider a rename of branches to make that more clear.

**Comment by bast** [comment]
This PR got closed while I was renaming branches. Please use the current `master` as base for your work instead of the "old" `master` which has been renamed to `stable-1.x`.

**Pull request closed without merging**
