### PR TITLE
Prepare release 2.1.0

### PR DESCRIPTION
**Pull request by robertodr**
Prepare the next release

## Todos

* **Developer Interest**

  - [X] Updated `version_info.hpp` with version bump
  - [x] Updated `xcfun.cmake` with version bump
  - [x] Updated `conf.py` with version bump
  - [x] Updated C++, C, and Fortran host examples with version bump
  - [x] Updated `CHANGELOG.md`
  - [x] Updated `.zenodo.json`
  - [x] Updated documentation to include new ways of installing the package (conda and spack)

## Status

- [x]  Ready to go

### CODE REVIEW

**Comment by robertodr** [comment]
@bast do we want to pull in also #127? It is very close to the finish line...

**Review by stigrj — APPROVED** [review]

**Comment by bast** [comment]
> @bast do we want to pull in also #127? It is very close to the finish line...

catching up now (email deluge ...). i am looking at #127

**Comment by bast** [comment]
#127 is now in and I made it conflict. Should we rebase this PR?

**Comment by robertodr** [comment]
Just rebased.

**Review by bast — APPROVED** [review]
Also thanks for listing James in the zenodo file.

**Pull request merged**
