### PR TITLE
Update Autocmake

### PR DESCRIPTION
**Pull request by robertodr**
Updates Autocmake and the date on the licensing headers.

## Status

- [x]  Ready to go

### CODE REVIEW

**Comment by simensr** [comment]
This looks good. But, I would prefer to set it to merge when the CI has completed. Two questions:

1. is the CI now working?
2. is it possible to set it to merge once the CI is completed?

**Comment by robertodr** [comment]
1. CI works. It was fixed by Radovan a couple of days ago.
2. Merge-on-success is not available on GitHub, as far as I know. It could be done with a Git hook and some permission magic repo-side.

**Comment by simensr** [comment]
Ok, great. Then I'll simply wait for the CI to complete first.

**Comment by robertodr** [comment]
Uff, I made a stupid mistake. I am on it.

**Comment by robertodr** [comment]
Seems CI is fixed... I suggest squashing and merging.

**Pull request merged**
