### PR TITLE
Adding python interface for calculation of energy density only

### PR DESCRIPTION
**Pull request by chjacob-tubs**
I extended the Python interface a but to allow the calculation of the energy density only (without calculating the potential). We are going to use this functionality in PyADF.

## How Has This Been Tested?
A test of the interface is included in PyADF (as for the rest of the interface)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Questions

- [ ]  Question1

## Status

- [x]  Ready to go

### CODE REVIEW

**Comment by chjacob-tubs** [comment]
Thanks @robertodr I changed the error messages, will look at the tests tomorrow.

**Comment by chjacob-tubs** [comment]
OK, the python tests are a bigger task (see #43), but I promised earlier to look at this. Hope I will find some time for this tomorrow.

**Comment by chjacob-tubs** [comment]
@robertodr I added tests of the Python interface and use Pytest for the tests now. The automatic tests still fail because pytest is not available in the test environment. How can I fix that?

**Comment by chjacob-tubs** [comment]
Thanks! I will merge this once the automatic tests pass.

On the Python 2.7 question: This is all part of a larger cleanup effort and I hope then we will be able to migrate all our code to Python 3. We are not completely there yet but getting closer...

**Comment by bast** [comment]
Thanks a lot for this!

**Pull request merged**
