### PR TITLE
Fixed clang error: call to 'cbrt' is ambiguous

### PR DESCRIPTION
**Pull request by yurivict**
This resolves https://github.com/dftlibs/xcfun/issues/22

### CODE REVIEW

**Comment by robertodr** [comment]
Thank you! The continuous integration builds on Travis are currently failing. Let's wait until @uekstrom and/or other developers can have a say.

**Comment by uekstrom** [comment]
The "correct" way would be to figure out what numeric type (T=double etc) libtaylor uses, and do cbrt(T(2)) to get the cube root with the right precision. But I support this commit because it is consistent with other constants in the code, which are in double precision.

**Comment by robertodr** [comment]
Thanks Ulf for weighing in. I have two questions:
1. Should all similar instances in XCFun be tracked down and corrected in a similar way?
2. Just out of curiosity, is there a way to implement the correct approach?

**Comment by uekstrom** [comment]
It is not so easy to do cleanly, see how to extend numeric_limits in c++
with your own numeric type. Using double is almost always the right choice.

Ulf

**Comment by robertodr** [comment]
Would a construct using [`std::is_same`](http://en.cppreference.com/w/cpp/types/is_same) do the trick? It's C++11 though...

**Comment by uekstrom** [comment]
It's not immediate clear to me how the code would look. The problem is that the return value of sqrt(x) is based on the type of x, not on the type assigned to. We have the same problem with constants such as pi. C solved this nicely in the "C world" by using doubles, but I don't know if there is a general solution in C++. The QD high precision library struggles with this issues as well. Of course anything is possible if you accept ugly code, but the formulas a difficult enough to read as it is. C++11 is no problem, I wish I had time to rewrite the whole library in more modern C++.

**Pull request merged**
